version: '3.7'
name: bb4-dev
services:
  db:
    image: postgres:14.8
    container_name: bb_dev_db
    restart: always
    environment:
      POSTGRES_PASSWORD: 3Q2ernEv51dr
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    command: postgres -c max_locks_per_transaction=2000
    logging:
      options:
        max-size: '10m'
        max-file: '3'

  graphql:
    image: hasura/graphql-engine:v2.39.1
    container_name: bb_dev_graphql
    ports:
      - '8080:8080'
    depends_on:
      - db
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:3Q2ernEv51dr@db:5432/bb
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'

volumes:
  db_data:
